# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMRCheck', '0002_auto_20170821_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omrsubmitmodel',
            name='email',
            field=models.CharField(default='xyz@mail.com', max_length=30),
        ),
    ]
