# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OMRCheck', '0004_auto_20170821_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omrsubmitmodel',
            old_name='username',
            new_name='username_id',
        ),
    ]
