# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMRCheck', '0005_auto_20170821_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omrsubmitmodel',
            name='username_id',
        ),
        migrations.AddField(
            model_name='omrsubmitmodel',
            name='Name',
            field=models.CharField(default='xyz', max_length=200),
        ),
    ]
