# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMRCheck', '0012_auto_20170822_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='Username',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
