# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OMRCheck', '0013_auto_20170822_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregister',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='studentregister',
            name='RollNo',
        ),
    ]
