# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMRCheck', '0014_auto_20170822_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='Username',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
