# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMRCheck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omrsubmitmodel',
            name='username',
        ),
        migrations.AddField(
            model_name='omrsubmitmodel',
            name='email',
            field=models.CharField(default='xyz@mail.com', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='Email',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='Username',
            field=models.CharField(default='xyz', max_length=200),
        ),
    ]
