# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OMRCheck', '0003_auto_20170821_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='omrsubmitmodel',
            name='phone',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AddField(
            model_name='omrsubmitmodel',
            name='username',
            field=models.ForeignKey(default='name', on_delete=django.db.models.deletion.CASCADE, to='OMRCheck.StudentRegister'),
        ),
        migrations.AlterField(
            model_name='omrsubmitmodel',
            name='email',
            field=models.CharField(default='----', max_length=30),
        ),
        migrations.AlterField(
            model_name='omrsubmitmodel',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
