# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMRCheck', '0010_auto_20170822_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregister',
            name='Email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='Username',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
