# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-03 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='name',
            field=models.CharField(default='Barkha', max_length=5000),
        ),
    ]
