# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 19:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegister',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Name: Only alphabets are allowed.')])),
                ('email', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Name: Only alphabets are allowed.')])),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OMRSubmitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omrsheet', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('Username', models.CharField(default='xyz', max_length=200, primary_key=True, serialize=False)),
                ('Name', models.CharField(default='xyz', max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]*$', 'Name: Only alphabets are allowed.')])),
                ('RollNo', models.CharField(default='xyz', max_length=10)),
                ('Class', models.CharField(default='xyz', max_length=15)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(default='1234567890', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Phone: Invalid Phone Number')])),
            ],
        ),
        migrations.AddField(
            model_name='omrsubmitmodel',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMRCheck.StudentRegister'),
        ),
    ]
